
/*
 * Copyright (C) 2018-2019 Edward Lu
 *
 * This file is subject to the terms and conditions of the GNU Lesser
 * General Public License v2.1. See the file LICENSE in the top level
 * directory for more details.
 */

package NDNLiteSupport.SignOnBasicControllerBLE.secureSignOn;

public class SignOnControllerResultCodes {
    public enum SignOnControllerResultCode {
        SUCCESS,
        ERROR_PROCESSING_UNRECOGNIZED_MESSAGE_TYPE,
        ERROR_PROCESSING_BOOTSTRAPPING_REQUEST_ERROR_PARSING,
        ERROR_PROCESSING_BOOTSTRAPPING_REQUEST_DEVICE_IDENTIFIER_NOT_FOUND_IN_DEVICE_LIST,
        ERROR_PROCESSING_BOOTSTRAPPING_REQUEST_FAILED_TO_VERIFY,
        ERROR_PROCESSING_BOOTSTRAPPING_REQUEST_FAILED_TO_GENERATE_N2_KEY_PAIR,
        ERROR_CONSTRUCTING_BOOTSTRAPPING_REQUEST_RESPONSE_ERROR_ADDING_N2_PUB_RAW_BYTES,
        ERROR_CONSTRUCTING_BOOTSTRAPPING_REQUEST_RESPONSE_ERROR_ADDING_TRUST_ANCHOR_CERTIFICATE,
        ERROR_PROCESSING_CERTIFICATE_REQUEST_ERROR_PARSING,
        ERROR_PROCESSING_CERTIFICATE_REQUEST_DEVICE_IDENTIFIER_NOT_FOUND_IN_DEVICE_LIST,
        ERROR_PROCESSING_CERTIFICATE_REQUEST_FAILED_TO_VERIFY,
        ERROR_PROCESSING_CERTIFICATE_REQUEST_FAILED_TO_GENERATE_TRUST_ANCHOR_DIGEST,
        ERROR_PROCESSING_CERTIFICATE_REQUEST_TRUST_ANCHOR_DIGEST_DID_NOT_MATCH,
        ERROR_PROCESSING_CERTIFICATE_REQUEST_N1_PUB_DID_NOT_MATCH,
        ERROR_PROCESSING_CERTIFICATE_REQUEST_FAILED_TO_GENERATE_N2_PUB_DIGEST,
        ERROR_PROCESSING_CERTIFICATE_REQUEST_N2_PUB_DIGEST_DID_NOT_MATCH,
        ERROR_PROCESSING_CERTIFICATE_REQUEST_FAILED_TO_CONVERT_N1_PUB_TO_PUBLIC_KEY_OBJECT,
        ERROR_PROCESSING_CERTIFICATE_REQUEST_FAILED_TO_DERIVE_DIFFIE_HELLMAN_SHARED_SECRET,
        ERROR_CONSTRUCTING_CERTIFICATE_REQUEST_RESPONSE_FAILED_TO_GENERATE_KEYPAIR_FOR_DEVICE,
        ERROR_CONSTRUCTING_CERTIFICATE_REQUEST_RESPONSE_FAILED_TO_GENERATE_CERTIFICATE_FOR_DEVICE,
        ERROR_CONSTRUCTING_CERTIFICATE_REQUEST_RESPONSE_ERROR_ADDING_ENCRYPTED_KD_PRI,
        ERROR_CONSTRUCTING_CERTIFICATE_REQUEST_RESPONSE_ERROR_ADDING_KD_PUB_CERTIFICATE,
        ERROR_PROCESSING_FINISH_MESSAGE_ERROR_PARSING,
        ERROR_PROCESSING_FINISH_MESSAGE_DEVICE_IDENTIFIER_NOT_FOUND_IN_DEVICE_LIST,
        ERROR_PROCESSING_FINISH_MESSAGE_FAILED_TO_VERIFY,
        ERROR_PROCESSING_FINISH_MESSAGE_DEVICE_INDICATED_THAT_SIGN_ON_FAILED,
    }
}
