
/*
 * Copyright (C) 2018-2019 Edward Lu
 *
 * This file is subject to the terms and conditions of the GNU Lesser
 * General Public License v2.1. See the file LICENSE in the top level
 * directory for more details.
 */

package NDNLiteSupport.SignOnBasicControllerBLE.secureSignOn;

import net.named_data.jndn.security.v2.CertificateV2;

import java.security.KeyPair;
import java.security.PublicKey;

public class SignOnDeviceInfo {
    public String deviceIdentifierHexString = null; // device identifier of device, in hex string format
    public CertificateV2 KSpubCertificate = null; // public key certificate of "Key Shared" key pair's public key
    public PublicKey KSpub = null; // "Key Shared" public key in PublicKey object format, extracted from the KSpubCertificate
    public byte[] KT = null; // "Key temporal", the shared secret generated through diffie hellman
    public byte[] secureSignOnCode = null; // preshared secure sign on code between controller and device
    public KeyPair N2KeyPair = null; // N2 keypair, keypair generated by controller for diffie hellman exchange
    public byte[] N2pubRawBytes = null; // N2 public key in byte array format
    public byte[] N1pubRawBytes = null; // N1 public key in byte array format
    public KeyPair KDKeyPair = null; // "Key Device", key pair generated by controller for use by device
    public CertificateV2 KDPubCertificate = null; // public key certificate of "Key Device" key pair's public key
    public boolean onboarded = false; // will be true if onboarding has successfully completed for this device
}
